name: evidential
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - xarray
  - netcdf4
  - dask
  - pandas
  - scikit-learn
  - pyyaml
  - pytest
  - distributed
  - pip
  - pyproj
  - jupyter
  - jupyterlab
  - cartopy
  - tqdm
  - sphinx
  - numba
  - cython
  - pip:
    - torch
    - pyarrow
    - fastparquet
    - hagelslag
    - imblearn
    - .

numpy~=1.23.5
torch~=1.13.1
scikit-learn~=1.2.1
tqdm~=4.64.1
matplotlib~=3.7.0
cartopy~=0.21.1
setuptools~=67.3.2