name: evidential
channels:
  - conda-forge
dependencies:
  - python =3.8
  - numpy ~=1.23.5
  - scipy
  - matplotlib ~=3.7.0
  - xarray
  - netcdf4
  - dask
  - pandas
  - scikit-learn ~=1.2.1
  - pyyaml
  - pytest
  - distributed
  - pip
  - pyproj
  - jupyter
  - jupyterlab
  - cartopy ~=0.21.1
  - tqdm ~=4.64.1
  - sphinx
  - numba
  - cython
  - pip:
    - torch ~=1.13.1
    - pyarrow
    - fastparquet
    - hagelslag
    - imblearn
    - .
