save_loc: "/glade/work/schreck/repos/evidential/evidential/results/mlp"

data_seed: 0
model_seed: 0

input_cols: [
    'wind_speed:10_m:m_s-1',
    'potential_temperature_skin_change:10_m:K_m-1',
    'bulk_richardson:10_m:None',
    'mixing_ratio_skin_change:2_m:g_kg-1_m-1'
]
output_cols: [
    #"friction_velocity:surface:m_s-1",
    "kinematic_sensible_heat_flux:surface:K_m_s-1",
    #"kinematic_latent_heat_flux:surface:g_kg-1_m_s-1"
]

idaho: "/glade/p/cisl/aiml/fasteddy/idaho_derived_data_20210720.csv"
cabauw: "/glade/p/cisl/aiml/fasteddy/cabauw_derived_data_20210720.csv"
use_idaho: 1
use_cabauw: 0

# Get the shapes of the input and output data 
model_type: "mlp"
input_size: 4
middle_size: 4500
output_size: 1
weight_init: "xavier"

epochs: 1000
batch_size: 256
L1_penalty: 0.0
L2_penalty: 0.0
dropout: 0.0
batch_norm: 0

metric: 'val_mae'
lr_patience: 5
stopping_patience: 20
learning_rate: 1.0e-04
clip: 1.0
loss_coeff: 0.05