seed: 1000
save_loc: "/glade/work/schreck/repos/evidential/main/results"

data:
    save_loc: "/glade/p/cisl/aiml/ai2es/surfacelayer/cabauw_derived_data_20210720.csv"
    input_cols: [
        'wind_speed:10_m:m_s-1',
        'potential_temperature_skin_change:10_m:K_m-1',
        'bulk_richardson:10_m:None',
        'mixing_ratio_skin_change:2_m:g_kg-1_m-1'
    ]
    output_cols: [
        'friction_velocity:surface:m_s-1', 
        'kinematic_sensible_heat_flux:surface:K_m_s-1', 
        'kinematic_latent_heat_flux:surface:g_kg-1_m_s-1'
    ]
    splitter: "GroupShuffleSplit"
    scaler:
        x: "StandardScaler"
        y: "StandardScaler"
    split_col: "day"
    n_splits: 3

model:
    hidden_layers: 4
    hidden_neurons: 256
    activation: "relu"
    optimizer: "adam"
    metrics: "mae"
    evidential_coef: 0.0
    uncertainties: False
    lr: 0.00001
    kernel_reg: 'l2'
    l1_weight: 0.0
    l2_weight: 0.0000001
    batch_size: 256
    use_noise: False
    noise_sd: 0.0
    use_dropout: False
    dropout_alpha: 0.2
    epochs: 1
    verbose: 2
    
    
callbacks:
  EarlyStopping:
    monitor: "val_mae"
    patience: 5
    mode: "min"
    verbose: 1
  ReduceLROnPlateau: 
    monitor: "val_mae"
    factor: 0.1
    patience: 2
    min_lr: 1.0e-12
    min_delta: 1.0e-08
    mode: "min"
    verbose: 1
  CSVLogger:
    filename: "training_log.txt"
    separator: " "
    append: False
  ModelCheckpoint:
    filepath: "model.h5"
    monitor: "val_mae"
    save_weights: True
    save_best_only: True
    mode: "min"
    verbose: 1